#!/usr/bin/env bash
set -e

# The directory this script is in.
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd -P)"
PARSER="node $SCRIPT_DIR/parser"

$PARSER setup --quiet

if [[ -z $1 ]]; then
  echo -n "Specify the starting tag: "
  read TAG
else
  TAG=$1
fi

if [[ -n $2 ]]; then
  TAG="$1..$2"
  HEADER="#### Changelog for $2\n*Previous tag: $1*"
else
  HEADER="#### Changelog"
fi

echo -e "$HEADER"

git --no-pager log --reverse --no-merges --format='* %s' "$TAG" | $PARSER parse
